name: Build Moodle Docker Image

on:
  schedule:
    - cron: '0 0 */14 * *'  # toutes les 2 semaines à minuit
  workflow_dispatch:       # permet un déclenchement manuel

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ghcr.io/calaxo/moodle-docker:latest

    permissions:
      contents: read
      packages: write

    steps:
      # 1. Checkout le repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Installer Docker (si ce n’est pas déjà disponible)
      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      # 3. Login GHCR
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4. Build l’image Docker
      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME .

      # 5. Push l’image sur GHCR
      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME
